const CLASSIFICATION_SETS = [
  {
    id: "classify-ancient-polity",
    title: "고대 국가 분류",
    era: "고대",
    priority: "S",
    prompt: "어느 나라와 연결되는가?",
    labels: ["고구려", "백제", "신라", "발해", "가야"],
    cards: [
      { term: "광개토 대왕", answer: "고구려", priority: "S", note: "광개토 대왕은 고구려의 왕이다." },
      { term: "영락", answer: "고구려", priority: "S", note: "영락은 고구려 광개토 대왕의 연호이다." },
      { term: "경당", answer: "고구려", priority: "A", note: "경당은 고구려의 지방 교육 기관이다." },
      { term: "욕살", answer: "고구려", priority: "A", note: "욕살은 고구려의 지방관이다." },
      { term: "동맹", answer: "고구려", priority: "S", note: "동맹은 고구려의 제천 행사이다." },
      { term: "안동도호부", answer: "고구려", priority: "A", note: "당은 고구려 멸망 뒤 평양에 안동도호부를 설치하였다." },
      { term: "근초고왕", answer: "백제", priority: "S", note: "근초고왕은 백제의 왕이다." },
      { term: "고흥", answer: "백제", priority: "A", note: "고흥은 백제 근초고왕 때 서기를 편찬하였다." },
      { term: "무령왕", answer: "백제", priority: "S", note: "무령왕은 백제의 왕이다." },
      { term: "22담로", answer: "백제", priority: "S", note: "22담로는 백제 무령왕의 지방 통치와 연결된다." },
      { term: "6좌평", answer: "백제", priority: "A", note: "6좌평은 백제의 관제이다." },
      { term: "부여풍", answer: "백제", priority: "A", note: "부여풍은 백제 부흥 운동을 이끌었다." },
      { term: "지증왕", answer: "신라", priority: "S", note: "지증왕은 신라의 왕이다." },
      { term: "법흥왕", answer: "신라", priority: "S", note: "법흥왕은 신라의 왕이다." },
      { term: "진흥왕", answer: "신라", priority: "S", note: "진흥왕은 신라의 왕이다." },
      { term: "화랑도", answer: "신라", priority: "S", note: "화랑도는 신라 진흥왕 때 국가 조직으로 정비되었다." },
      { term: "황룡사 9층 목탑", answer: "신라", priority: "S", note: "황룡사 9층 목탑은 신라 선덕 여왕 때 건립되었다." },
      { term: "외사정", answer: "신라", priority: "A", note: "외사정은 통일 신라의 지방관 감찰과 연결된다." },
      { term: "장문휴", answer: "발해", priority: "S", note: "장문휴는 발해 무왕의 명으로 당의 등주를 공격하였다." },
      { term: "상경 용천부", answer: "발해", priority: "S", note: "상경 용천부는 발해 문왕이 천도한 수도이다." },
      { term: "대흥", answer: "발해", priority: "A", note: "대흥은 발해 문왕의 연호이다." },
      { term: "5경 15부 62주", answer: "발해", priority: "S", note: "5경 15부 62주는 발해 선왕 때 정비되었다." },
      { term: "중정대", answer: "발해", priority: "A", note: "중정대는 발해의 관리 감찰 기관이다." },
      { term: "정효공주", answer: "발해", priority: "A", note: "정효공주는 발해 문왕의 딸이다." },
      { term: "금관가야", answer: "가야", priority: "S", note: "금관가야는 가야 연맹의 한 나라이다." },
      { term: "덩이쇠", answer: "가야", priority: "S", note: "덩이쇠는 금관가야의 교역품이자 화폐처럼 쓰였다." },
      { term: "포상팔국의 난", answer: "가야", priority: "A", note: "포상팔국의 난은 가야 세력과 신라의 관계를 보여 준다." }
    ]
  },
  {
    id: "classify-goryeo-domain",
    title: "고려 핵심 영역 분류",
    era: "고려",
    priority: "S",
    prompt: "어떤 영역의 핵심 개념인가?",
    labels: ["왕·정책", "대외 항쟁", "무신 정권", "제도·문화"],
    cards: [
      { term: "노비안검법", answer: "왕·정책", priority: "S", note: "광종의 왕권 강화 정책이다." },
      { term: "과거제", answer: "왕·정책", priority: "S", note: "광종이 쌍기의 건의를 받아 시행하였다." },
      { term: "최승로 시무 28조", answer: "왕·정책", priority: "S", note: "성종의 유교 통치 체제 정비와 연결된다." },
      { term: "12목", answer: "왕·정책", priority: "S", note: "성종이 지방관을 파견한 주요 행정 구역이다." },
      { term: "별무반", answer: "왕·정책", priority: "S", note: "숙종 때 윤관의 건의로 편성하였다." },
      { term: "동북 9성", answer: "왕·정책", priority: "S", note: "예종 때 윤관이 여진을 정벌하고 축조하였다." },
      { term: "김윤후", answer: "대외 항쟁", priority: "S", note: "김윤후는 몽골 침입 때 처인성과 충주산성에서 항전하였다." },
      { term: "처인성", answer: "대외 항쟁", priority: "S", note: "처인성은 몽골군에 맞선 대표 항쟁지이다." },
      { term: "살리타", answer: "대외 항쟁", priority: "S", note: "몽골 장수 살리타는 처인성 전투에서 사살되었다." },
      { term: "충주산성", answer: "대외 항쟁", priority: "A", note: "김윤후가 주민을 이끌고 몽골군에 항전한 곳이다." },
      { term: "나성", answer: "대외 항쟁", priority: "A", note: "현종이 거란과의 전쟁 뒤 개경 방어를 위해 축조하였다." },
      { term: "관음포 전투", answer: "대외 항쟁", priority: "A", note: "정지가 왜구를 격파한 전투이다." },
      { term: "최충헌", answer: "무신 정권", priority: "S", note: "최충헌은 교정도감을 설치한 무신 집권자이다." },
      { term: "교정도감", answer: "무신 정권", priority: "S", note: "최충헌이 설치한 최고 권력 기구이다." },
      { term: "최우", answer: "무신 정권", priority: "S", note: "최우는 정방과 서방을 설치하였다." },
      { term: "정방", answer: "무신 정권", priority: "S", note: "최우가 설치한 인사 행정 기구이다." },
      { term: "서방", answer: "무신 정권", priority: "A", note: "최우가 문인을 등용해 자문받은 기구이다." },
      { term: "야별초", answer: "무신 정권", priority: "A", note: "최우가 개경 치안을 위해 조직하였다." },
      { term: "시정 전시과", answer: "제도·문화", priority: "A", note: "경종 때 처음 마련된 토지 제도이다." },
      { term: "경정 전시과", answer: "제도·문화", priority: "A", note: "문종 때 완성된 전시과이다." },
      { term: "음서제", answer: "제도·문화", priority: "A", note: "고려의 관리 등용 제도이다." },
      { term: "도병마사", answer: "제도·문화", priority: "A", note: "고려의 국방·군사 회의 기구이다." },
      { term: "김부식", answer: "제도·문화", priority: "A", note: "김부식은 삼국사기를 편찬하였다." },
      { term: "최충", answer: "제도·문화", priority: "A", note: "최충은 9재 학당을 세운 유학자이다." }
    ]
  },
  {
    id: "classify-joseon-domain",
    title: "조선 핵심 영역 분류",
    era: "조선",
    priority: "S",
    prompt: "어떤 영역과 연결되는가?",
    labels: ["왕·정책", "중앙 관청", "전쟁·항쟁", "사상·문화", "후기 사회"],
    cards: [
      { term: "공법", answer: "왕·정책", priority: "S", note: "세종이 마련한 전세 제도이다." },
      { term: "직전법", answer: "왕·정책", priority: "S", note: "세조 때 시행된 토지 제도이다." },
      { term: "관수관급제", answer: "왕·정책", priority: "S", note: "성종 때 시행된 토지 제도이다." },
      { term: "대동법", answer: "왕·정책", priority: "S", note: "광해군 때 경기도에서 처음 시행되었다." },
      { term: "균역법", answer: "왕·정책", priority: "S", note: "영조가 군포 부담을 줄인 군역 제도이다." },
      { term: "신해통공", answer: "왕·정책", priority: "S", note: "정조가 육의전을 제외한 금난전권을 폐지한 조치이다." },
      { term: "사간원", answer: "중앙 관청", priority: "S", note: "간쟁과 논박을 담당한 3사이다." },
      { term: "사헌부", answer: "중앙 관청", priority: "S", note: "관리 비리 감찰을 담당한 3사이다." },
      { term: "홍문관", answer: "중앙 관청", priority: "S", note: "경연을 담당하고 옥당이라 불린 관청이다." },
      { term: "승정원", answer: "중앙 관청", priority: "S", note: "왕명 출납을 맡은 왕의 비서 기관이다." },
      { term: "비변사", answer: "중앙 관청", priority: "S", note: "조선의 국방 문제를 논의한 기구이다." },
      { term: "훈련도감", answer: "중앙 관청", priority: "S", note: "임진왜란 중 설치된 중앙 군영이다." },
      { term: "송상현", answer: "전쟁·항쟁", priority: "S", note: "임진왜란 때 동래성에서 항전하였다." },
      { term: "정문부", answer: "전쟁·항쟁", priority: "S", note: "임진왜란 때 길주에서 의병을 이끌었다." },
      { term: "정봉수·이립", answer: "전쟁·항쟁", priority: "S", note: "정묘호란 때 용골산성에서 항전하였다." },
      { term: "임경업", answer: "전쟁·항쟁", priority: "S", note: "병자호란 때 백마산성에서 항전하였다." },
      { term: "김준룡", answer: "전쟁·항쟁", priority: "S", note: "병자호란 때 광교산에서 청군을 격퇴하였다." },
      { term: "김상용", answer: "전쟁·항쟁", priority: "S", note: "병자호란 때 강화도에서 순절하였다." },
      { term: "이황", answer: "사상·문화", priority: "A", note: "주자서절요와 성학십도를 남긴 성리학자이다." },
      { term: "이이", answer: "사상·문화", priority: "A", note: "성학집요를 저술한 성리학자이다." },
      { term: "김장생", answer: "사상·문화", priority: "A", note: "가례집람을 저술한 예학자이다." },
      { term: "정약용", answer: "사상·문화", priority: "A", note: "목민심서 등을 저술한 실학자이다." },
      { term: "홍경래의 난", answer: "후기 사회", priority: "A", note: "순조 때 평안도 차별 등에 반발해 일어났다." },
      { term: "임술 농민 봉기", answer: "후기 사회", priority: "S", note: "철종 때 삼정의 문란을 배경으로 확산되었다." },
      { term: "삼정이정청", answer: "후기 사회", priority: "S", note: "임술 농민 봉기 뒤 삼정 개혁을 위해 설치하였다." },
      { term: "신해박해", answer: "후기 사회", priority: "A", note: "정조 때 일어난 천주교 박해이다." },
      { term: "신유박해", answer: "후기 사회", priority: "A", note: "순조 때 일어난 천주교 박해이다." }
    ]
  },
  {
    id: "classify-opening-movement",
    title: "개항기 운동 성격 분류",
    era: "개항기",
    priority: "S",
    prompt: "어떤 흐름에 속하는가?",
    labels: ["개화·개혁", "위정척사", "계몽·교육", "국권 수호·의거"],
    cards: [
      { term: "강화도 조약", answer: "개화·개혁", priority: "S", note: "조선이 일본과 맺은 최초의 근대적 조약이다." },
      { term: "별기군", answer: "개화·개혁", priority: "A", note: "개화 정책 과정에서 창설된 신식 군대이다." },
      { term: "1차 갑오개혁", answer: "개화·개혁", priority: "S", note: "군국기무처가 추진한 근대적 개혁이다." },
      { term: "탁지아문", answer: "개화·개혁", priority: "S", note: "1차 갑오개혁 때 재정을 일원화한 관청이다." },
      { term: "홍범 14조", answer: "개화·개혁", priority: "S", note: "2차 갑오개혁 때 반포하였다." },
      { term: "단발령", answer: "개화·개혁", priority: "S", note: "을미개혁 때 시행하였다." },
      { term: "최익현", answer: "위정척사", priority: "S", note: "왜양일체론을 내세워 개항에 반대하였다." },
      { term: "왜양일체론", answer: "위정척사", priority: "S", note: "일본과 서양이 본질적으로 같다는 위정척사 논리이다." },
      { term: "영남 만인소", answer: "위정척사", priority: "S", note: "조선책략 유포에 반대하여 올린 상소이다." },
      { term: "조선책략", answer: "위정척사", priority: "A", note: "영남 유생의 위정척사 운동을 촉발하였다." },
      { term: "독립협회", answer: "계몽·교육", priority: "S", note: "자주 국권과 의회 설립을 추진한 계몽 단체이다." },
      { term: "대한자강회", answer: "계몽·교육", priority: "A", note: "교육과 식산흥업을 강조한 애국 계몽 단체이다." },
      { term: "신민회", answer: "계몽·교육", priority: "S", note: "교육·산업 활동과 독립운동 기지 건설을 추진하였다." },
      { term: "태극서관", answer: "계몽·교육", priority: "S", note: "신민회가 계몽 서적 보급을 위해 설립하였다." },
      { term: "오산 학교", answer: "계몽·교육", priority: "S", note: "신민회 계열 이승훈이 세운 민족 교육 기관이다." },
      { term: "국채 보상 운동", answer: "국권 수호·의거", priority: "S", note: "국민의 힘으로 일본에 진 빚을 갚으려 한 운동이다." },
      { term: "김광제·서상돈", answer: "국권 수호·의거", priority: "S", note: "국채 보상 운동을 발의하였다." },
      { term: "장인환·전명운", answer: "국권 수호·의거", priority: "A", note: "친일 외교 고문 스티븐스를 저격하였다." },
      { term: "안중근", answer: "국권 수호·의거", priority: "S", note: "하얼빈에서 이토 히로부미를 처단하였다." },
      { term: "양헌수", answer: "국권 수호·의거", priority: "S", note: "병인양요 때 정족산성에서 프랑스군을 격퇴하였다." }
    ]
  },
  {
    id: "classify-japanese-movement",
    title: "일제 강점기 운동 분류",
    era: "일제강점기",
    priority: "S",
    prompt: "어떤 독립운동 흐름인가?",
    labels: ["국내 민족운동", "의열 투쟁", "만주 무장투쟁", "해외 기반·외교"],
    cards: [
      { term: "신간회", answer: "국내 민족운동", priority: "S", note: "민족주의와 사회주의 세력이 연대한 국내 단체이다." },
      { term: "정우회 선언", answer: "국내 민족운동", priority: "S", note: "신간회 결성에 영향을 준 선언이다." },
      { term: "광주 학생 항일 운동", answer: "국내 민족운동", priority: "S", note: "학생 중심으로 전국에 확산된 항일 운동이다." },
      { term: "성진회", answer: "국내 민족운동", priority: "S", note: "광주 학생 항일 운동의 기반이 된 비밀 결사이다." },
      { term: "형평사", answer: "국내 민족운동", priority: "A", note: "백정 차별 철폐를 주장한 국내 사회 운동 단체이다." },
      { term: "원산 총파업", answer: "국내 민족운동", priority: "A", note: "1929년에 전개된 대표 노동 운동이다." },
      { term: "의열단", answer: "의열 투쟁", priority: "S", note: "김원봉이 조직한 의열 투쟁 단체이다." },
      { term: "김원봉", answer: "의열 투쟁", priority: "S", note: "의열단 조직을 주도하였다." },
      { term: "나석주", answer: "의열 투쟁", priority: "S", note: "동양 척식 주식회사에 폭탄을 투척하였다." },
      { term: "동양 척식 주식회사", answer: "의열 투쟁", priority: "S", note: "나석주 의거의 공격 대상이다." },
      { term: "대한광복회", answer: "의열 투쟁", priority: "S", note: "친일파 처단과 군자금 모집 활동을 전개하였다." },
      { term: "박상진", answer: "의열 투쟁", priority: "S", note: "대한광복회 총사령으로 활동하였다." },
      { term: "대한 독립군", answer: "만주 무장투쟁", priority: "S", note: "홍범도가 이끈 북간도의 독립군 부대이다." },
      { term: "봉오동 전투", answer: "만주 무장투쟁", priority: "S", note: "홍범도 부대 등이 승리한 만주의 독립 전쟁이다." },
      { term: "청산리 대첩", answer: "만주 무장투쟁", priority: "S", note: "김좌진 부대 등이 일본군을 격파한 전투이다." },
      { term: "한국 독립군", answer: "만주 무장투쟁", priority: "S", note: "지청천이 이끌고 중국군과 연합 작전을 전개하였다." },
      { term: "조선 혁명군", answer: "만주 무장투쟁", priority: "S", note: "중국 의용군과 연합하여 영릉가·흥경성에서 싸웠다." },
      { term: "대전자령 전투", answer: "만주 무장투쟁", priority: "S", note: "한국 독립군이 중국군과 연합해 승리한 전투이다." },
      { term: "권업회", answer: "해외 기반·외교", priority: "A", note: "연해주에서 활동하며 권업신문을 발간하였다." },
      { term: "흥사단", answer: "해외 기반·외교", priority: "A", note: "안창호가 미국 샌프란시스코에서 창립하였다." },
      { term: "경학사", answer: "해외 기반·외교", priority: "A", note: "서간도에 조직된 한인 자치 기관이다." },
      { term: "신한청년당", answer: "해외 기반·외교", priority: "S", note: "김규식을 파리 강화 회의에 파견하였다." },
      { term: "김규식", answer: "해외 기반·외교", priority: "S", note: "파리 강화 회의에서 독립을 청원하였다." },
      { term: "한인 비행 학교", answer: "해외 기반·외교", priority: "A", note: "노백린이 미국 캘리포니아에 세운 군사 교육 기반이다." }
    ]
  },
  {
    id: "classify-modern-government",
    title: "현대사 정부·민주화 분류",
    era: "현대사",
    priority: "A",
    prompt: "어느 정부·민주화 흐름인가?",
    labels: ["이승만·4·19", "박정희 정부", "전두환·민주화", "노태우 정부", "김영삼 이후"],
    cards: [
      { term: "발췌 개헌", answer: "이승만·4·19", priority: "S", note: "이승만 정부 때 대통령 직선제를 골자로 통과되었다." },
      { term: "조봉암", answer: "이승만·4·19", priority: "A", note: "이승만 정부 때 진보당 사건으로 구속되었다." },
      { term: "김주열", answer: "이승만·4·19", priority: "S", note: "김주열의 희생은 4·19 혁명 확산의 계기가 되었다." },
      { term: "제2공화국", answer: "이승만·4·19", priority: "A", note: "4·19 혁명 뒤 출범하였다." },
      { term: "국가재건최고회의", answer: "박정희 정부", priority: "S", note: "5·16 군사 정변 세력이 구성한 최고 통치 기구이다." },
      { term: "민청학련 사건", answer: "박정희 정부", priority: "A", note: "박정희 정부가 학생과 반정부 인사를 탄압한 사건이다." },
      { term: "새마을 운동", answer: "박정희 정부", priority: "A", note: "박정희 정부 시기에 추진된 농촌 근대화 운동이다." },
      { term: "3·1 민주 구국 선언", answer: "박정희 정부", priority: "A", note: "유신 체제에 반대한 민주화 운동이다." },
      { term: "국가보위비상대책위원회", answer: "전두환·민주화", priority: "S", note: "신군부가 설치하고 전두환이 상임위원장을 맡았다." },
      { term: "5·18 민주화 운동", answer: "전두환·민주화", priority: "S", note: "1980년 광주에서 전개된 민주화 운동이다." },
      { term: "시민군", answer: "전두환·민주화", priority: "S", note: "5·18 민주화 운동 때 계엄군에 맞서 조직되었다." },
      { term: "6월 민주 항쟁", answer: "전두환·민주화", priority: "S", note: "1987년 대통령 직선제 개헌을 요구한 민주화 운동이다." },
      { term: "6·29 민주화 선언", answer: "전두환·민주화", priority: "S", note: "6월 민주 항쟁 결과 직선제 개헌을 수용한 선언이다." },
      { term: "7·7 선언", answer: "노태우 정부", priority: "S", note: "남북 교류와 사회주의 국가와의 관계 개선을 추진하였다." },
      { term: "남북 기본 합의서", answer: "노태우 정부", priority: "S", note: "노태우 정부 때 채택되었다." },
      { term: "강경대", answer: "노태우 정부", priority: "A", note: "노태우 정부 시기 민주화 시위 중 희생되었다." },
      { term: "민주노총 창립", answer: "김영삼 이후", priority: "A", note: "김영삼 정부 때인 1995년에 창립 대회가 열렸다." },
      { term: "국민기초생활보장법", answer: "김영삼 이후", priority: "A", note: "김대중 정부 때 제정되어 시행되었다." },
      { term: "노사정위원회", answer: "김영삼 이후", priority: "A", note: "김대중 정부가 외환 위기 극복을 위해 구성하였다." },
      { term: "호주제 폐지", answer: "김영삼 이후", priority: "A", note: "노무현 정부 때 호주제가 폐지되었다." }
    ]
  }
];
