const PAIRS = [
  { id: "ancient-paleolithic-chipped-stone", left: "구석기 시대", right: "뗀석기", era: "고대", category: "시대-유물", priority: "S", explanation: "구석기 시대에는 돌을 깨뜨려 만든 뗀석기를 사용하였다.", source: "한능검.md" },
  { id: "ancient-neolithic-spindle-bone-needle", left: "신석기 시대", right: "가락바퀴·뼈바늘", era: "고대", category: "시대-유물", priority: "S", explanation: "신석기 시대의 가락바퀴와 뼈바늘은 원시적 수공업과 의생활을 보여 준다.", source: "한능검.md" },
  { id: "ancient-bronze-bipa-dagger", left: "청동기 시대", right: "비파형 동검", era: "고대", category: "시대-유물", priority: "S", explanation: "비파형 동검은 청동기 시대의 대표적인 유물이다.", source: "한능검.md" },
  { id: "ancient-iron-chinese-coins", left: "철기 시대", right: "명도전·반량전", era: "고대", category: "시대-유물", priority: "A", explanation: "명도전과 반량전은 철기 시대에 중국과 교류했음을 보여 주는 화폐 유물이다.", source: "한능검.md" },
  { id: "ancient-gojoseon-eight-laws", left: "고조선", right: "8조법", era: "고대", category: "국가-제도", priority: "S", explanation: "고조선은 8조법으로 사회 질서를 유지하였다.", source: "한능검.md" },
  { id: "ancient-buyeo-yeonggo", left: "부여", right: "영고", era: "고대", category: "국가-제천", priority: "S", explanation: "부여는 12월에 제천 행사 영고를 열었다.", source: "한능검.md" },
  { id: "ancient-buyeo-sachuldo", left: "부여", right: "사출도", era: "고대", category: "국가-제도", priority: "A", explanation: "부여에서는 마가·우가·저가·구가가 사출도를 다스렸다.", source: "한능검.md" },
  { id: "ancient-goguryeo-dongmaeng", left: "고구려", right: "동맹", era: "고대", category: "국가-제천", priority: "S", explanation: "고구려는 10월에 제천 행사 동맹을 열었다.", source: "한능검.md" },
  { id: "ancient-okjeo-minmyeoneuri", left: "옥저", right: "민며느리제", era: "고대", category: "국가-풍습", priority: "S", explanation: "옥저에는 어린 며느리를 데려와 성장시킨 뒤 혼인하는 민며느리제가 있었다.", source: "한능검.md" },
  { id: "ancient-okjeo-goljangje", left: "옥저", right: "골장제", era: "고대", category: "국가-풍습", priority: "A", explanation: "옥저에서는 가족의 뼈를 추려 공동 무덤에 안치하는 골장제를 행하였다.", source: "한능검.md" },
  { id: "ancient-dongye-mucheon", left: "동예", right: "무천", era: "고대", category: "국가-제천", priority: "S", explanation: "동예는 10월에 제천 행사 무천을 열었다.", source: "한능검.md" },
  { id: "ancient-dongye-chaekhwa", left: "동예", right: "책화", era: "고대", category: "국가-풍습", priority: "A", explanation: "동예에서는 다른 읍락의 영역을 침범하면 배상하게 하는 책화가 있었다.", source: "한능검.md" },
  { id: "ancient-samhan-sodo", left: "삼한", right: "소도", era: "고대", category: "국가-제도", priority: "S", explanation: "삼한의 소도는 천군이 제사를 주관한 신성 지역이었다.", source: "한능검.md" },
  { id: "ancient-goguryeo-gwanggaeto-yeongnak", left: "광개토 대왕", right: "영락", era: "고대", category: "왕-정책", priority: "S", explanation: "고구려 광개토 대왕은 독자적 연호 영락을 사용하였다.", source: "한능검.md" },
  { id: "ancient-goguryeo-jangsu-punghong", left: "장수왕", right: "풍홍", era: "고대", category: "왕-사건", priority: "B", explanation: "장수왕은 북연 멸망 뒤 풍홍을 받아들였으나 왕으로 높이지 않았다.", source: "한능검.md" },
  { id: "ancient-goguryeo-gyeongdang", left: "경당", right: "경전·활쏘기", era: "고대", category: "제도-특징", priority: "A", explanation: "고구려 지방 교육 기관 경당에서는 경전과 활쏘기를 가르쳤다.", source: "한능검.md" },
  { id: "ancient-baekje-geunchogo-seogi", left: "근초고왕", right: "서기", era: "고대", category: "왕-문화", priority: "S", explanation: "백제 근초고왕은 고흥에게 역사서 서기를 편찬하게 하였다.", source: "한능검.md" },
  { id: "ancient-baekje-gaero-northernwei", left: "개로왕", right: "북위에 고구려 공격 요청", era: "고대", category: "왕-외교", priority: "B", explanation: "개로왕은 북위에 사신을 보내 고구려 공격을 요청하였다.", source: "한능검.md" },
  { id: "ancient-baekje-muryeong-22damro", left: "무령왕", right: "22담로", era: "고대", category: "왕-정책", priority: "S", explanation: "백제 무령왕은 지방 22담로에 왕족을 파견하였다.", source: "한능검.md" },
  { id: "ancient-baekje-goi-6jwapyeong", left: "고이왕", right: "6좌평", era: "고대", category: "왕-제도", priority: "A", explanation: "고이왕은 내신좌평 등 6좌평과 관등제를 정비한 왕으로 정리한다.", source: "한능검.md" },
  { id: "ancient-baekje-buyeopung-baekgang", left: "부여풍", right: "백강 전투", era: "고대", category: "인물-사건", priority: "B", explanation: "부여풍은 왜군과 함께 백강 전투에서 당군에 맞섰다.", source: "한능검.md" },
  { id: "ancient-silla-beopheung-geonwon", left: "법흥왕", right: "건원", era: "고대", category: "왕-정책", priority: "S", explanation: "신라 법흥왕은 독자적 연호 건원을 사용하였다.", source: "한능검.md" },
  { id: "ancient-silla-beopheung-byeongbu", left: "법흥왕", right: "병부", era: "고대", category: "왕-제도", priority: "S", explanation: "법흥왕은 병부를 설치하였다.", source: "한능검.md" },
  { id: "ancient-silla-beopheung-sangdaedeung", left: "법흥왕", right: "상대등", era: "고대", category: "왕-제도", priority: "A", explanation: "법흥왕은 상대등을 설치하였다.", source: "한능검.md" },
  { id: "ancient-silla-jijeung-ugyeong", left: "지증왕", right: "우경", era: "고대", category: "왕-정책", priority: "S", explanation: "신라 지증왕은 우경을 장려하였다.", source: "한능검.md" },
  { id: "ancient-silla-jijeung-dongsijeon", left: "지증왕", right: "동시전", era: "고대", category: "왕-제도", priority: "S", explanation: "지증왕은 시장 감독 관청인 동시전을 설치하였다.", source: "한능검.md" },
  { id: "ancient-silla-jinheung-guksa", left: "진흥왕", right: "국사", era: "고대", category: "왕-문화", priority: "S", explanation: "진흥왕은 거칠부에게 명해 역사서 국사를 편찬하게 하였다.", source: "한능검.md" },
  { id: "ancient-silla-jinheung-hwarangdo", left: "진흥왕", right: "화랑도", era: "고대", category: "왕-제도", priority: "S", explanation: "진흥왕은 화랑도를 국가적 조직으로 개편하였다.", source: "한능검.md" },
  { id: "ancient-silla-jinheung-pumju", left: "진흥왕", right: "품주", era: "고대", category: "왕-제도", priority: "A", explanation: "진흥왕은 조세와 국가 재정을 맡은 품주를 정비하였다.", source: "한능검.md" },
  { id: "ancient-silla-jinheung-gaeguk", left: "진흥왕", right: "개국·대창·홍제", era: "고대", category: "왕-정책", priority: "A", explanation: "진흥왕은 개국·대창·홍제 등의 독자적 연호를 사용하였다.", source: "한능검.md" },
  { id: "ancient-silla-seondeok-hwangnyongsa", left: "선덕 여왕", right: "황룡사 9층 목탑", era: "고대", category: "왕-문화", priority: "S", explanation: "선덕 여왕은 자장의 건의로 황룡사 9층 목탑을 건립하였다.", source: "한능검.md" },
  { id: "ancient-silla-munmu-oesajeong", left: "문무왕", right: "외사정", era: "고대", category: "왕-제도", priority: "A", explanation: "문무왕은 지방관 감찰을 위해 외사정을 파견하였다.", source: "한능검.md" },
  { id: "ancient-silla-sangsuri-localcontrol", left: "상수리 제도", right: "지방 세력 통제", era: "고대", category: "제도-특징", priority: "B", explanation: "상수리 제도는 지방 세력 자제나 관리를 수도에 머물게 한 지방 통제 제도이다.", source: "한능검.md" },
  { id: "ancient-silla-gangsu-cheongbang", left: "강수", right: "청방인문표", era: "고대", category: "인물-저술", priority: "C", explanation: "강수는 당에 보낸 청방인문표의 글을 지었다.", source: "한능검.md" },
  { id: "ancient-silla-hyecho-wangocheonchuk", left: "혜초", right: "왕오천축국전", era: "고대", category: "인물-저술", priority: "A", explanation: "혜초는 구법 순례기 왕오천축국전을 저술하였다.", source: "한능검.md" },
  { id: "ancient-silla-jinseong-wonjon-aeno", left: "진성 여왕", right: "원종과 애노의 난", era: "고대", category: "왕-사건", priority: "A", explanation: "진성 여왕 때 원종과 애노의 난이 일어났다.", source: "한능검.md" },
  { id: "ancient-silla-choechiwon-haeinsa", left: "최치원", right: "해인사 묘길상탑기", era: "고대", category: "인물-저술", priority: "B", explanation: "최치원은 신라 말 사회상을 보여 주는 해인사 묘길상탑기를 남겼다.", source: "한능검.md" },
  { id: "ancient-silla-kimalji-samgukyusa", left: "김알지 신화", right: "삼국유사", era: "고대", category: "사건-특징", priority: "B", explanation: "김알지 신화는 삼국유사에 실려 있다.", source: "한능검.md" },
  { id: "ancient-balhae-muwang-jangmunhyu", left: "발해 무왕", right: "장문휴", era: "고대", category: "왕-군사", priority: "S", explanation: "발해 무왕은 장문휴를 보내 당의 등주를 선제 공격하였다.", source: "한능검.md" },
  { id: "ancient-balhae-munwang-sanggyeong", left: "발해 문왕", right: "상경 용천부", era: "고대", category: "왕-정책", priority: "S", explanation: "발해 문왕은 수도를 상경 용천부로 옮겼다.", source: "한능검.md" },
  { id: "ancient-balhae-munwang-3sung6bu", left: "발해 문왕", right: "3성 6부", era: "고대", category: "왕-제도", priority: "A", explanation: "발해 문왕은 중앙 관제를 3성 6부 체제로 정비하였다.", source: "한능검.md" },
  { id: "ancient-balhae-munwang-daeheung", left: "발해 문왕", right: "대흥", era: "고대", category: "왕-정책", priority: "A", explanation: "발해 문왕은 독자적 연호 대흥을 사용하였다.", source: "한능검.md" },
  { id: "ancient-balhae-seonwang-5gyeong", left: "발해 선왕", right: "5경 15부 62주", era: "고대", category: "왕-제도", priority: "S", explanation: "발해 선왕은 지방 행정 조직을 5경 15부 62주로 정비하였다.", source: "한능검.md" },
  { id: "ancient-balhae-jungjeongdae", left: "발해", right: "중정대", era: "고대", category: "제도-시대", priority: "B", explanation: "발해는 관리 감찰 기관으로 중정대를 두었다.", source: "한능검.md" },
  { id: "ancient-gaya-geumgwan-deongisoe", left: "금관가야", right: "덩이쇠", era: "고대", category: "국가-특징", priority: "A", explanation: "금관가야에서는 덩이쇠를 화폐처럼 사용하고 교역품으로 활용하였다.", source: "한능검.md" },
  { id: "ancient-tang-goguryeo-andong", left: "고구려 멸망", right: "안동도호부", era: "고대", category: "사건-특징", priority: "A", explanation: "고구려 멸망 뒤 당은 평양에 안동도호부를 설치하였다.", source: "한능검.md" },
  { id: "ancient-tang-baekje-ungjin", left: "백제 멸망", right: "웅진도독부", era: "고대", category: "사건-특징", priority: "A", explanation: "백제 멸망 뒤 당은 웅진에 웅진도독부를 설치하였다.", source: "한능검.md" },
  { id: "later3-hubaekje-hudang-owol", left: "후백제", right: "후당·오월", era: "후삼국", category: "국가-외교", priority: "C", explanation: "후백제는 후당·오월에 사신을 파견하였다.", source: "한능검.md" },
  { id: "later3-gungye-gwangpyeongseong", left: "궁예", right: "광평성", era: "후삼국", category: "인물-제도", priority: "A", explanation: "궁예는 광평성을 비롯한 여러 관부를 설치하였다.", source: "한능검.md" },
  { id: "goryeo-taejo-cheonsu", left: "태조 왕건", right: "천수", era: "고려", category: "왕-정책", priority: "S", explanation: "태조 왕건은 독자적 연호 천수를 사용하였다.", source: "한능검.md" },
  { id: "goryeo-taejo-yeokbunjeon", left: "태조 왕건", right: "역분전", era: "고려", category: "왕-토지", priority: "A", explanation: "태조 왕건은 후삼국 통일 과정의 공로를 기준으로 역분전을 지급하였다.", source: "한능검.md" },
  { id: "goryeo-taejo-georan", left: "태조 왕건", right: "거란 적대", era: "고려", category: "왕-외교", priority: "A", explanation: "태조 왕건은 발해를 멸망시킨 거란을 적대하였다.", source: "한능검.md" },
  { id: "goryeo-taejo-jeonggye", left: "태조 왕건", right: "정계·계백료서", era: "고려", category: "왕-저술", priority: "A", explanation: "태조 왕건은 정계와 계백료서를 저술하였다.", source: "한능검.md" },
  { id: "goryeo-jeongjong-wanggyu", left: "정종", right: "왕규의 난", era: "고려", category: "왕-사건", priority: "B", explanation: "정종은 왕규의 난을 진압하였다.", source: "한능검.md" },
  { id: "goryeo-gwangjong-gwangdeok", left: "광종", right: "광덕·준풍", era: "고려", category: "왕-정책", priority: "A", explanation: "광종은 독자적 연호 광덕·준풍을 사용하였다.", source: "한능검.md" },
  { id: "goryeo-gwangjong-slave-review", left: "광종", right: "노비안검법", era: "고려", category: "왕-정책", priority: "S", explanation: "광종은 불법적으로 노비가 된 사람을 양인으로 회복시키는 노비안검법을 실시하였다.", source: "한능검.md" },
  { id: "goryeo-gwangjong-gwageo", left: "광종", right: "과거제", era: "고려", category: "왕-제도", priority: "S", explanation: "광종은 쌍기의 건의를 받아 과거제를 실시하였다.", source: "한능검.md" },
  { id: "goryeo-seongjong-12mok", left: "성종", right: "12목", era: "고려", category: "왕-정책", priority: "S", explanation: "성종은 전국 주요 지역인 12목에 지방관을 파견하였다.", source: "한능검.md" },
  { id: "goryeo-seongjong-choeseungro", left: "성종", right: "최승로 시무 28조", era: "고려", category: "왕-정책", priority: "S", explanation: "성종은 최승로의 시무 28조를 받아들여 유교 정치 체제를 정비하였다.", source: "한능검.md" },
  { id: "goryeo-gyeongjong-sijeong-jeonsigwa", left: "경종", right: "시정 전시과", era: "고려", category: "왕-토지", priority: "A", explanation: "경종 때 관품과 인품을 반영한 시정 전시과가 처음 마련되었다.", source: "한능검.md" },
  { id: "goryeo-mokjong-gaejeong-jeonsigwa", left: "목종", right: "개정 전시과", era: "고려", category: "왕-토지", priority: "A", explanation: "목종 때 관품을 중심으로 토지를 지급하는 개정 전시과가 시행되었다.", source: "한능검.md" },
  { id: "goryeo-munjong-gyeongjeong-jeonsigwa", left: "문종", right: "경정 전시과", era: "고려", category: "왕-토지", priority: "A", explanation: "문종 때 현직 관리 중심으로 경정 전시과가 완성되었다.", source: "한능검.md" },
  { id: "goryeo-gongeumjeon-hereditary", left: "공음전", right: "세습 가능", era: "고려", category: "제도-특징", priority: "A", explanation: "공음전은 5품 이상 관리에게 지급되어 자손에게 세습할 수 있었다.", source: "한능검.md" },
  { id: "goryeo-seongjong-geonwonjungbo", left: "성종", right: "건원중보", era: "고려", category: "왕-경제", priority: "A", explanation: "성종은 금속 화폐 건원중보를 주조하였다.", source: "한능검.md" },
  { id: "goryeo-seongjong-gyeongsiseo", left: "성종", right: "경시서", era: "고려", category: "왕-제도", priority: "B", explanation: "성종은 시장 감독 관청 경시서를 두었다.", source: "한능검.md" },
  { id: "goryeo-seongjong-sangpyeongchang", left: "성종", right: "상평창", era: "고려", category: "왕-제도", priority: "B", explanation: "성종은 물가 조절과 빈민 구제를 위한 상평창을 두었다.", source: "한능검.md" },
  { id: "goryeo-munjong-choechung-9jae", left: "최충", right: "9재 학당", era: "고려", category: "인물-교육", priority: "A", explanation: "문종 때 최충은 9재 학당을 열었다.", source: "한능검.md" },
  { id: "goryeo-choechung-munheongongdo", left: "최충", right: "문헌공도", era: "고려", category: "인물-교육", priority: "A", explanation: "최충의 학당은 문헌공도라 불렸고 사학 12도 발달에 영향을 주었다.", source: "한능검.md" },
  { id: "goryeo-sukjong-haedongtongbo", left: "숙종", right: "해동통보", era: "고려", category: "왕-경제", priority: "S", explanation: "숙종은 해동통보를 발행하여 화폐 유통을 추진하였다.", source: "한능검.md" },
  { id: "goryeo-sukjong-hwalgu", left: "숙종", right: "활구", era: "고려", category: "왕-경제", priority: "A", explanation: "숙종은 은병인 활구를 발행하였다.", source: "한능검.md" },
  { id: "goryeo-sukjong-jujeondogam", left: "숙종", right: "주전도감", era: "고려", category: "왕-경제", priority: "S", explanation: "숙종은 의천의 건의에 따라 주전도감을 설치하였다.", source: "한능검.md" },
  { id: "goryeo-sukjong-byeolmuban", left: "숙종", right: "별무반", era: "고려", category: "왕-군사", priority: "S", explanation: "숙종 때 윤관의 건의로 별무반을 편성하였다.", source: "한능검.md" },
  { id: "goryeo-sukjong-seojeokpo", left: "숙종", right: "서적포", era: "고려", category: "왕-문화", priority: "B", explanation: "숙종은 국자감에 출판 기관 서적포를 설치하였다.", source: "한능검.md" },
  { id: "goryeo-yejong-dongbuk9", left: "예종", right: "동북 9성", era: "고려", category: "왕-군사", priority: "S", explanation: "예종 때 윤관이 여진을 정벌하고 동북 9성을 축조하였다.", source: "한능검.md" },
  { id: "goryeo-mokjong-gimchiyang", left: "목종", right: "김치양 제거", era: "고려", category: "왕-사건", priority: "C", explanation: "목종 때 강조가 정변을 일으켜 김치양을 제거하였다.", source: "한능검.md" },
  { id: "goryeo-injong-myochung", left: "인종", right: "묘청의 서경 천도 운동", era: "고려", category: "왕-사건", priority: "S", explanation: "인종 때 묘청의 서경 천도 운동이 일어났다.", source: "한능검.md" },
  { id: "goryeo-chungmok-jeongchidogam", left: "충목왕", right: "정치도감", era: "고려", category: "왕-제도", priority: "A", explanation: "충목왕은 폐정 개혁을 목표로 정치도감을 설치하였다.", source: "한능검.md" },
  { id: "goryeo-gongmin-seonggyungwan", left: "공민왕", right: "성균관", era: "고려", category: "왕-교육", priority: "A", explanation: "공민왕은 국자감을 성균관으로 개칭하였다.", source: "한능검.md" },
  { id: "goryeo-eumseo-5pum", left: "음서제", right: "5품 이상 관리 자손", era: "고려", category: "제도-특징", priority: "A", explanation: "음서제는 문무 5품 이상 관리의 자손 등에게 관직 진출 기회를 준 제도이다.", source: "한능검.md" },
  { id: "goryeo-hyeonjong-naseong", left: "현종", right: "나성", era: "고려", category: "왕-군사", priority: "A", explanation: "현종은 거란과의 전쟁 뒤 개경 방어를 위해 나성을 축조하였다.", source: "한능검.md" },
  { id: "goryeo-gimyunu-cheoinseong", left: "김윤후", right: "처인성", era: "고려", category: "인물-사건", priority: "S", explanation: "김윤후는 처인부곡민의 처인성 항전을 이끌었다.", source: "한능검.md" },
  { id: "goryeo-gimyunu-sallitai", left: "김윤후", right: "살리타", era: "고려", category: "인물-사건", priority: "S", explanation: "김윤후가 이끈 처인부곡민은 처인성에서 몽골 장수 살리타를 사살하였다.", source: "한능검.md" },
  { id: "goryeo-gimyunu-chungjusanseong", left: "김윤후", right: "충주산성", era: "고려", category: "인물-사건", priority: "A", explanation: "김윤후는 몽골의 5차 침입 때 충주산성에서 주민을 이끌고 항전하였다.", source: "한능검.md" },
  { id: "goryeo-sambyeolcho-yongjangseong", left: "삼별초", right: "용장성", era: "고려", category: "단체-활동", priority: "A", explanation: "삼별초는 진도로 이동하여 용장성을 쌓고 항전하였다.", source: "한능검.md" },
  { id: "goryeo-jeongji-gwaneumpo", left: "정지", right: "관음포 전투", era: "고려", category: "인물-사건", priority: "A", explanation: "우왕 때 정지는 관음포 전투에서 왜구를 격파하였다.", source: "한능검.md" },
  { id: "goryeo-choechungheon-gyojeongdogam", left: "최충헌", right: "교정도감", era: "고려", category: "인물-제도", priority: "S", explanation: "최충헌은 무신 정권 최고 권력 기구인 교정도감을 설치하였다.", source: "한능검.md" },
  { id: "goryeo-choeu-jeongbang", left: "최우", right: "정방", era: "고려", category: "인물-제도", priority: "S", explanation: "최우는 인사 행정 기구 정방을 설치하였다.", source: "한능검.md" },
  { id: "goryeo-choeu-seobang", left: "최우", right: "서방", era: "고려", category: "인물-제도", priority: "A", explanation: "최우는 문인을 등용하고 정치 자문을 받기 위해 서방을 설치하였다.", source: "한능검.md" },
  { id: "goryeo-sambyeolcho-yabyeolcho", left: "삼별초", right: "야별초", era: "고려", category: "단체-유래", priority: "S", explanation: "삼별초는 최우가 개경 치안을 위해 조직한 야별초에서 시작하였다.", source: "한능검.md" },
  { id: "goryeo-samsa-accounting", left: "삼사", right: "출납·회계", era: "고려", category: "관청-기능", priority: "A", explanation: "고려 삼사는 화폐와 곡식의 출납·회계를 담당하였다.", source: "한능검.md" },
  { id: "goryeo-dobyeongmasa-defense", left: "도병마사", right: "국방·군사", era: "고려", category: "관청-기능", priority: "A", explanation: "도병마사는 주로 국방·군사 문제를 논의하였다.", source: "한능검.md" },
  { id: "goryeo-sikmokdogam-law", left: "식목도감", right: "법제·격식", era: "고려", category: "관청-기능", priority: "A", explanation: "식목도감은 주로 법제와 격식을 논의하였다.", source: "한능검.md" },
  { id: "goryeo-daegan-bongbak", left: "대간", right: "봉박·간쟁·서경권", era: "고려", category: "제도-기능", priority: "A", explanation: "고려 대간은 봉박·간쟁·서경권을 행사하였다.", source: "한능검.md" },
  { id: "goryeo-kimbusik-samguksagi", left: "김부식", right: "삼국사기", era: "고려", category: "인물-저술", priority: "A", explanation: "김부식은 기전체 역사서 삼국사기를 편찬하였다.", source: "한능검.md" },
  { id: "joseon-saganwon-ganjaeng", left: "사간원", right: "간쟁", era: "조선", category: "관청-기능", priority: "S", explanation: "사간원은 국왕 정책에 대한 간쟁과 논박을 담당하였다.", source: "한능검.md" },
  { id: "joseon-sejong-gongbeop", left: "세종", right: "공법", era: "조선", category: "왕-수취", priority: "S", explanation: "세종은 토지의 비옥도와 풍흉을 반영하는 공법을 마련하였다.", source: "한능검.md" },
  { id: "joseon-gongbeop-jeonbun-yeonbun", left: "공법", right: "전분 6등법·연분 9등법", era: "조선", category: "제도-특징", priority: "A", explanation: "공법은 토지 비옥도를 따지는 전분 6등법과 풍흉을 따지는 연분 9등법으로 구성되었다.", source: "한능검.md" },
  { id: "joseon-gwanghae-daedong-gyeonggi", left: "광해군", right: "대동법 경기도 실시", era: "조선", category: "왕-수취", priority: "S", explanation: "광해군 때 대동법이 경기도에서 처음 시행되었다.", source: "한능검.md" },
  { id: "joseon-daedongbeop-gongin", left: "대동법", right: "공인 등장", era: "조선", category: "제도-영향", priority: "S", explanation: "대동법 시행으로 국가에 관수품을 납품하는 공인이 등장하였다.", source: "한능검.md" },
  { id: "joseon-yeongjo-gyunyeok", left: "영조", right: "균역법", era: "조선", category: "왕-수취", priority: "S", explanation: "영조는 군역 부담을 줄이기 위해 균역법을 시행하였다.", source: "한능검.md" },
  { id: "joseon-gyunyeok-one-pil", left: "균역법", right: "군포 1필", era: "조선", category: "제도-특징", priority: "S", explanation: "균역법은 양인 장정이 부담하던 군포를 1년에 2필에서 1필로 줄였다.", source: "한능검.md" },
  { id: "joseon-seonjo-hunryeondogam", left: "선조", right: "훈련도감", era: "조선", category: "왕-군사", priority: "S", explanation: "선조 때 임진왜란 중 훈련도감이 설치되었다.", source: "한능검.md" },
  { id: "joseon-yeongjo-sokdaejeon", left: "영조", right: "속대전", era: "조선", category: "왕-법전", priority: "A", explanation: "영조 때 조선 후기의 법령을 정리한 속대전이 편찬되었다.", source: "한능검.md" },
  { id: "joseon-saheonbu-gamchal", left: "사헌부", right: "감찰", era: "조선", category: "관청-기능", priority: "S", explanation: "사헌부는 관리 비리 감찰과 풍속 교화를 담당하였다.", source: "한능검.md" },
  { id: "joseon-hongmungwan-gyeongyeon", left: "홍문관", right: "경연", era: "조선", category: "관청-기능", priority: "S", explanation: "홍문관은 경연을 담당하였다.", source: "한능검.md" },
  { id: "joseon-hongmungwan-okdang", left: "홍문관", right: "옥당", era: "조선", category: "관청-별칭", priority: "A", explanation: "홍문관은 옥당이라고도 불렸다.", source: "한능검.md" },
  { id: "joseon-seungjeongwon-royalorder", left: "승정원", right: "왕명 출납", era: "조선", category: "관청-기능", priority: "S", explanation: "승정원은 왕명의 출납을 맡은 왕의 비서 기관이다.", source: "한능검.md" },
  { id: "joseon-sejo-jikjeonbeop", left: "세조", right: "직전법", era: "조선", category: "왕-정책", priority: "S", explanation: "세조는 과전법을 직전법으로 바꾸고 수신전·휼양전을 폐지하였다.", source: "한능검.md" },
  { id: "joseon-sejo-gangyeongdogam", left: "세조", right: "간경도감", era: "조선", category: "왕-문화", priority: "A", explanation: "세조는 불경을 한글로 번역·간행하기 위해 간경도감을 설치하였다.", source: "한능검.md" },
  { id: "joseon-sejo-isiae", left: "세조", right: "이시애의 난", era: "조선", category: "왕-사건", priority: "A", explanation: "세조 때 함길도 토착 세력 이시애가 난을 일으켰다.", source: "한능검.md" },
  { id: "joseon-seongjong-gwansugwan", left: "성종", right: "관수관급제", era: "조선", category: "왕-정책", priority: "S", explanation: "성종은 토지 수조권을 국가가 거두어 관리에게 지급하는 관수관급제를 실시하였다.", source: "한능검.md" },
  { id: "joseon-seongjong-hongmungwan", left: "성종", right: "홍문관", era: "조선", category: "왕-제도", priority: "A", explanation: "성종은 집현전을 계승한 홍문관을 설치하였다.", source: "한능검.md" },
  { id: "joseon-myeongjong-bibyeonsa", left: "명종", right: "비변사 상설", era: "조선", category: "왕-제도", priority: "S", explanation: "명종 때 을묘왜변을 계기로 비변사가 상설 기구화되었다.", source: "한능검.md" },
  { id: "joseon-myeongjong-guwhang", left: "명종", right: "구황촬요", era: "조선", category: "왕-문화", priority: "B", explanation: "명종은 기근 대비서 구황촬요를 간행·보급하였다.", source: "한능검.md" },
  { id: "joseon-myeongjong-jikjeon-abolish", left: "명종", right: "직전법 폐지", era: "조선", category: "왕-정책", priority: "A", explanation: "명종 때 직전법이 폐지되었다.", source: "한능검.md" },
  { id: "joseon-injo-yeongjeongbeop", left: "인조", right: "영정법", era: "조선", category: "왕-정책", priority: "S", explanation: "인조는 풍흉과 관계없이 전세를 1결당 4두로 고정하는 영정법을 시행하였다.", source: "한능검.md" },
  { id: "joseon-sukjong-sangpyeongtongbo", left: "숙종", right: "상평통보", era: "조선", category: "왕-경제", priority: "S", explanation: "숙종 때 상평통보가 널리 발행되어 법화로 사용되었다.", source: "한능검.md" },
  { id: "joseon-sukjong-geumwiyeong", left: "숙종", right: "금위영", era: "조선", category: "왕-군사", priority: "S", explanation: "숙종은 금위영을 설치하여 5군영 체제를 완성하였다.", source: "한능검.md" },
  { id: "joseon-sukjong-daebodan", left: "숙종", right: "대보단", era: "조선", category: "왕-제도", priority: "B", explanation: "숙종은 명 신종을 제사하는 대보단을 설치하였다.", source: "한능검.md" },
  { id: "joseon-jeongjo-sinhaetonggong", left: "정조", right: "신해통공", era: "조선", category: "왕-정책", priority: "S", explanation: "정조는 육의전을 제외한 시전 상인의 금난전권을 폐지하는 신해통공을 단행하였다.", source: "한능검.md" },
  { id: "joseon-jeongjo-sinhaebakhae", left: "정조", right: "신해박해", era: "조선", category: "왕-사건", priority: "B", explanation: "정조 때 신해박해가 일어났다.", source: "한능검.md" },
  { id: "joseon-cheoljong-samjeong", left: "철종", right: "삼정이정청", era: "조선", category: "왕-제도", priority: "S", explanation: "철종 때 임술 농민 봉기 뒤 삼정이정청을 설치하였다.", source: "한능검.md" },
  { id: "joseon-daewongun-daejeonhoetong", left: "흥선 대원군", right: "대전회통", era: "조선", category: "인물-정책", priority: "A", explanation: "흥선 대원군은 통치 체제 정비를 위해 대전회통을 편찬하였다.", source: "한능검.md" },
  { id: "joseon-yujeong-reply-envoy", left: "유정", right: "회답 겸 쇄환사", era: "조선", category: "인물-외교", priority: "B", explanation: "임진왜란 뒤 유정은 포로 송환을 위해 회답 겸 쇄환사로 파견되었다.", source: "한능검.md" },
  { id: "joseon-jungjong-sampo-bibyeonsa", left: "삼포 왜란", right: "비변사 설치", era: "조선", category: "사건-특징", priority: "A", explanation: "중종 때 삼포 왜란을 계기로 임시 기구 비변사가 설치되었다.", source: "한능검.md" },
  { id: "joseon-eulmyo-bibyeonsa", left: "을묘왜변", right: "비변사 상설", era: "조선", category: "사건-특징", priority: "A", explanation: "을묘왜변을 계기로 비변사가 상설 기구가 되었다.", source: "한능검.md" },
  { id: "joseon-songsanghyeon-dongnae", left: "송상현", right: "동래성", era: "조선", category: "인물-사건", priority: "S", explanation: "임진왜란 때 송상현은 동래성에서 항전하였다.", source: "한능검.md" },
  { id: "joseon-jeongmunbu-gilju", left: "정문부", right: "길주", era: "조선", category: "인물-사건", priority: "S", explanation: "임진왜란 때 정문부는 길주에서 의병을 이끌었다.", source: "한능검.md" },
  { id: "joseon-choeyundeok-imanjoo", left: "최윤덕", right: "올라산성·이만주", era: "조선", category: "인물-사건", priority: "A", explanation: "세종 때 최윤덕은 파저강 유역의 여진을 정벌했으며 올라산성·이만주가 대표 키워드이다.", source: "한능검.md" },
  { id: "joseon-jeongbongsu-yonggol", left: "정봉수·이립", right: "용골산성", era: "조선", category: "인물-사건", priority: "S", clue: "정묘호란 때 이 인물들은 용골산성에서 의병을 이끌고 항전하였다.", explanation: "정묘호란 때 정봉수와 이립은 용골산성에서 의병을 이끌고 항전하였다.", source: "한능검.md" },
  { id: "joseon-imgyeongeop-baekma", left: "임경업", right: "백마산성", era: "조선", category: "인물-사건", priority: "S", explanation: "병자호란 때 임경업은 백마산성에서 항전하였다.", source: "한능검.md" },
  { id: "joseon-gimjunryong-gwanggyo", left: "김준룡", right: "광교산", era: "조선", category: "인물-사건", priority: "S", explanation: "병자호란 때 김준룡은 용인 광교산에서 청군을 격퇴하였다.", source: "한능검.md" },
  { id: "joseon-gimsangyong-ganghwa", left: "김상용", right: "강화도", era: "조선", category: "인물-사건", priority: "S", explanation: "병자호란 때 김상용은 강화도에서 순절하였다.", source: "한능검.md" },
  { id: "joseon-yihwang-seonghaksipdo", left: "이황", right: "성학십도", era: "조선", category: "인물-저술", priority: "A", explanation: "이황은 성학십도를 저술하였다.", source: "한능검.md" },
  { id: "joseon-yihwang-sadanchiljeong", left: "이황", right: "사단칠정 논쟁", era: "조선", category: "인물-사건", priority: "B", explanation: "이황은 기대승과 사단칠정 논쟁을 벌였다.", source: "한능검.md" },
  { id: "joseon-yii-seonghakjibyo", left: "이이", right: "성학집요", era: "조선", category: "인물-저술", priority: "A", explanation: "이이는 성학집요를 저술하였다.", source: "한능검.md" },
  { id: "joseon-yii-donghomundap", left: "이이", right: "동호문답", era: "조선", category: "인물-저술", priority: "A", explanation: "이이는 동호문답에서 수취 제도 개혁 등을 제안하였다.", source: "한능검.md" },
  { id: "joseon-gimjangsaeng-garyejimram", left: "김장생", right: "가례집람", era: "조선", category: "인물-저술", priority: "B", explanation: "김장생은 예학서 가례집람을 저술하였다.", source: "한능검.md" },
  { id: "joseon-mokhoryong-sinimoksa", left: "목호룡의 고변", right: "신임옥사", era: "조선", category: "사건-특징", priority: "B", explanation: "경종 때 목호룡의 고변으로 신임옥사·신임사화가 전개되었다.", source: "한능검.md" },
  { id: "joseon-songsiyeol-gichukbongsa", left: "송시열", right: "기축봉사", era: "조선", category: "인물-저술", priority: "B", explanation: "송시열은 효종 즉위 직후 기축봉사를 올려 북벌론을 강조하였다.", source: "한능검.md" },
  { id: "joseon-yik-seonghosaseol", left: "이익", right: "성호사설", era: "조선", category: "인물-저술", priority: "A", explanation: "이익은 성호사설에서 나라를 좀먹는 여섯 폐단인 육좀을 지적하였다.", source: "한능검.md" },
  { id: "joseon-yisugwang-jibong", left: "이수광", right: "지봉유설", era: "조선", category: "인물-저술", priority: "A", explanation: "이수광은 지봉유설에서 천주실의를 소개하였다.", source: "한능검.md" },
  { id: "joseon-parkseedang-sabyeonrok", left: "박세당", right: "사변록·색경", era: "조선", category: "인물-저술", priority: "B", explanation: "박세당은 사변록과 농서 색경을 저술하였다.", source: "한능검.md" },
  { id: "joseon-ije-ma-donguisusebowon", left: "이제마", right: "동의수세보원", era: "조선", category: "인물-저술", priority: "A", explanation: "이제마는 동의수세보원을 편찬하여 사상 의학을 정립하였다.", source: "한능검.md" },
  { id: "joseon-gimjeongho-daedong", left: "김정호", right: "대동여지도", era: "조선", category: "인물-문화", priority: "A", explanation: "김정호의 대동여지도는 전체 22첩의 목판본으로 제작되었다.", source: "한능검.md" },
  { id: "joseon-gimjeonghui-bukhansanbi", left: "김정희", right: "북한산비 고증", era: "조선", category: "인물-문화", priority: "B", explanation: "김정희는 북한산비가 진흥왕 순수비임을 고증하였다.", source: "한능검.md" },
  { id: "joseon-sinhaebakhae-yunjichung", left: "신해박해", right: "윤지충", era: "조선", category: "사건-특징", priority: "A", explanation: "신해박해는 윤지충의 신주 소각 사건이 발단이 되었다.", source: "한능검.md" },
  { id: "joseon-sinyubakhae-hwangsayoung", left: "신유박해", right: "황사영 백서", era: "조선", category: "사건-특징", priority: "A", explanation: "신유박해 뒤 황사영이 외국 군대 출병을 요청하는 황사영 백서를 작성하였다.", source: "한능검.md" },
  { id: "joseon-honggyeongrae-jeongjuseong", left: "홍경래의 난", right: "정주성", era: "조선", category: "사건-특징", priority: "A", clue: "순조 때 일어나 정주성을 점령한 이 봉기는 무엇인가?", explanation: "순조 때 홍경래 등이 봉기하여 정주성을 점령하였다.", source: "한능검.md" },
  { id: "joseon-baeknaksin-jinju", left: "백낙신의 탐학", right: "진주 농민 봉기", era: "조선", category: "사건-특징", priority: "A", explanation: "철종 때 백낙신의 탐학을 계기로 진주에서 농민들이 봉기하였다.", source: "한능검.md" },
  { id: "joseon-bakgyusu-anhaeksa", left: "박규수", right: "안핵사", era: "조선", category: "인물-제도", priority: "A", explanation: "임술 농민 봉기 뒤 정부는 박규수를 안핵사로 파견하였다.", source: "한능검.md" },
  { id: "joseon-jobyeonggap-gobu", left: "조병갑", right: "고부 농민 봉기", era: "조선", category: "인물-사건", priority: "A", explanation: "고부 군수 조병갑의 횡포가 고부 농민 봉기의 직접적 배경이 되었다.", source: "한능검.md" },
  { id: "opening-choeikhyeon-waeyang", left: "최익현", right: "왜양일체론", era: "개항기", category: "인물-사상", priority: "S", explanation: "최익현은 일본과 서양이 본질적으로 같다는 왜양일체론으로 강화도 조약 체결에 반대하였다.", source: "한능검.md" },
  { id: "opening-ganghwa-coast-survey", left: "강화도 조약", right: "해안 측량권", era: "개항기", category: "조약-특징", priority: "S", explanation: "강화도 조약은 일본에 조선 해안 측량권을 허용한 불평등 조항을 담았다.", source: "한능검.md" },
  { id: "opening-joseon-us-good-offices", left: "조미 수호 통상 조약", right: "거중 조정", era: "개항기", category: "조약-특징", priority: "S", explanation: "조미 수호 통상 조약에는 제3국이 분쟁을 일으킬 때 서로 돕는 거중 조정 조항이 있었다.", source: "한능검.md" },
  { id: "opening-imo-jemulpo", left: "임오군란", right: "제물포 조약", era: "개항기", category: "사건-조약", priority: "S", explanation: "임오군란 뒤 조선은 일본과 제물포 조약을 체결하였다.", source: "한능검.md" },
  { id: "opening-eulmi-haircut", left: "을미개혁", right: "단발령", era: "개항기", category: "개혁-정책", priority: "S", explanation: "을미개혁 때 태양력 사용과 단발령 시행 등이 추진되었다.", source: "한능검.md" },
  { id: "opening-yeongnam-maninso-joseonchaekryak", left: "영남 만인소", right: "조선책략", era: "개항기", category: "사건-특징", priority: "S", explanation: "영남 만인소는 김홍집이 가져온 조선책략에 반대하여 올린 상소이다.", source: "한능검.md" },
  { id: "opening-byeolgigun-modern", left: "별기군", right: "교련병대", era: "개항기", category: "제도-특징", priority: "A", explanation: "별기군은 개화 정책 초기에 창설한 신식 군대이며 교련병대라고도 불렸다.", source: "한능검.md" },
  { id: "opening-yangheonsu-jeongjok", left: "양헌수", right: "정족산성", era: "개항기", category: "인물-사건", priority: "S", explanation: "병인양요 때 양헌수 부대가 정족산성에서 프랑스군을 격퇴하였다.", source: "한능검.md" },
  { id: "opening-gapsin-constitutional", left: "갑신정변", right: "입헌 군주제", era: "개항기", category: "사건-특징", priority: "A", explanation: "갑신정변은 입헌 군주제적 개혁을 지향하였다.", source: "한능검.md" },
  { id: "opening-gabo1-takji", left: "1차 갑오개혁", right: "탁지아문", era: "개항기", category: "사건-특징", priority: "S", explanation: "제1차 갑오개혁 때 탁지아문으로 재정을 일원화하였다.", source: "한능검.md" },
  { id: "opening-gabo1-nobi", left: "1차 갑오개혁", right: "공·사노비 제도 폐지", era: "개항기", category: "사건-특징", priority: "S", explanation: "제1차 갑오개혁 때 공·사노비 제도를 폐지하였다.", source: "한능검.md" },
  { id: "opening-gabo1-silver", left: "1차 갑오개혁", right: "은 본위제", era: "개항기", category: "사건-특징", priority: "A", explanation: "제1차 갑오개혁은 신식 화폐 발행 장정을 통해 은 본위제를 채택하였다.", source: "한능검.md" },
  { id: "opening-gabo2-hongbeom", left: "2차 갑오개혁", right: "홍범 14조", era: "개항기", category: "사건-특징", priority: "S", explanation: "제2차 갑오개혁 때 홍범 14조를 반포하였다.", source: "한능검.md" },
  { id: "opening-gabo2-23bu", left: "2차 갑오개혁", right: "23부", era: "개항기", category: "사건-특징", priority: "S", explanation: "제2차 갑오개혁 때 지방 행정 구역을 8도에서 23부로 개편하였다.", source: "한능검.md" },
  { id: "opening-gabo2-court", left: "2차 갑오개혁", right: "재판소", era: "개항기", category: "사건-특징", priority: "S", explanation: "제2차 갑오개혁 때 행정과 사법을 분리하여 재판소를 설치하였다.", source: "한능검.md" },
  { id: "opening-dongnip-jeoryeongdo", left: "독립협회", right: "절영도 조차 반대", era: "개항기", category: "단체-활동", priority: "S", explanation: "독립협회는 러시아의 절영도 조차 요구에 반대하였다.", source: "한능검.md" },
  { id: "opening-dongnip-parliament", left: "독립협회", right: "의회 설립 추진", era: "개항기", category: "단체-활동", priority: "A", explanation: "독립협회는 중추원 개편을 통해 의회 설립을 추진하였다.", source: "한능검.md" },
  { id: "opening-daehanjagang-king", left: "대한자강회", right: "고종 강제 퇴위 반대", era: "개항기", category: "단체-활동", priority: "A", explanation: "대한자강회는 고종 황제의 강제 퇴위에 반대하는 운동을 전개하였다.", source: "한능검.md" },
  { id: "opening-sinminhoe-taegeuk", left: "신민회", right: "태극서관", era: "개항기", category: "단체-활동", priority: "S", explanation: "신민회는 태극서관을 설립하여 계몽 서적을 보급하였다.", source: "한능검.md" },
  { id: "opening-sinminhoe-osan", left: "신민회", right: "오산 학교", era: "개항기", category: "단체-활동", priority: "S", explanation: "신민회 계열 이승훈은 인재 양성을 위해 오산 학교를 세웠다.", source: "한능검.md" },
  { id: "opening-hwangseong-yeogwon", left: "황성신문", right: "여권통문", era: "개항기", category: "단체-활동", priority: "B", explanation: "황성신문은 여성의 권리와 교육을 주장한 여권통문을 처음 보도하였다.", source: "한능검.md" },
  { id: "opening-daehanmaeil-uibyeong", left: "대한매일신보", right: "의병 투쟁 호의 보도", era: "개항기", category: "단체-활동", priority: "B", explanation: "대한매일신보는 의병 투쟁에 호의적인 기사를 게재하였다.", source: "한능검.md" },
  { id: "opening-gukchae-gimgwangje", left: "국채 보상 운동", right: "김광제·서상돈", era: "개항기", category: "사건-인물", priority: "S", explanation: "국채 보상 운동은 김광제·서상돈 등의 발의로 본격화되었다.", source: "한능검.md" },
  { id: "opening-gukchae-danyeonbo", left: "국채 보상 운동", right: "단연보국채", era: "개항기", category: "사건-특징", priority: "A", explanation: "장지연은 논설 단연보국채를 써서 국채 보상 운동에 참여하였다.", source: "한능검.md" },
  { id: "opening-jashinhoe-nacheol", left: "자신회", right: "나철·오기호", era: "개항기", category: "단체-인물", priority: "B", explanation: "나철·오기호 등은 을사오적 처단을 위해 자신회를 조직하였다.", source: "한능검.md" },
  { id: "opening-nacheol-daejonggyo", left: "나철", right: "대종교", era: "개항기", category: "인물-단체", priority: "A", explanation: "나철은 대종교를 창설하였다.", source: "한능검.md" },
  { id: "opening-jang-jeon-stevens", left: "장인환·전명운", right: "스티븐스 저격", era: "개항기", category: "인물-사건", priority: "A", explanation: "장인환·전명운은 친일 외교 고문 더럼 스티븐스를 저격하였다.", source: "한능검.md" },
  { id: "opening-anjunggeun-dongyang", left: "안중근", right: "동양평화론", era: "개항기", category: "인물-저술", priority: "A", explanation: "안중근은 동양평화론을 저술하였다.", source: "한능검.md" },
  { id: "japanese-land-survey-office", left: "토지 조사 사업", right: "임시 토지 조사국", era: "일제강점기", category: "사건-특징", priority: "A", explanation: "일제는 토지 조사 사업 추진을 위해 임시 토지 조사국을 설치하였다.", source: "한능검.md" },
  { id: "japanese-hyeongpyeongsa-1923", left: "형평사", right: "백정 차별 철폐", era: "일제강점기", category: "단체-활동", priority: "A", explanation: "형평사는 백정에 대한 차별 철폐를 주장하였다.", source: "한능검.md" },
  { id: "japanese-joseon-nodong-gongjehoe", left: "조선 노동 공제회", right: "1920", era: "일제강점기", category: "단체-시기", priority: "B", explanation: "조선 노동 공제회는 1920년에 조직된 전국적 노동 단체이다.", source: "한능검.md" },
  { id: "japanese-wonsan-1929", left: "원산 총파업", right: "1929", era: "일제강점기", category: "사건-시기", priority: "A", explanation: "원산 총파업은 1929년에 발생하였다.", source: "한능검.md" },
  { id: "japanese-mulsan-jajakhoe", left: "물산 장려 운동", right: "자작회·토산 애용 부인회", era: "일제강점기", category: "사건-단체", priority: "A", explanation: "물산 장려 운동에는 자작회·토산 애용 부인회 등이 활동하였다.", source: "한능검.md" },
  { id: "japanese-610-singanhoe", left: "6·10 만세 운동", right: "신간회 결성 영향", era: "일제강점기", category: "사건-특징", priority: "B", explanation: "6·10 만세 운동은 민족 협동 전선인 신간회 결성에 영향을 주었다.", source: "한능검.md" },
  { id: "japanese-gwangju-seongjinhoe", left: "광주 학생 항일 운동", right: "성진회", era: "일제강점기", category: "사건-특징", priority: "S", explanation: "광주 학생 항일 운동은 성진회와 각 학교 독서회를 통해 전국적으로 확산되었다.", source: "한능검.md" },
  { id: "japanese-singanhoe-jeonguhoe", left: "신간회", right: "정우회 선언", era: "일제강점기", category: "단체-활동", priority: "S", explanation: "신간회는 정우회 선언의 영향을 받아 결성되었다.", source: "한능검.md" },
  { id: "japanese-gwoneophoe-gwoneop", left: "권업회", right: "권업신문", era: "일제강점기", category: "단체-활동", priority: "A", explanation: "연해주에서 권업회가 설립되어 권업신문을 발간하였다.", source: "한능검.md" },
  { id: "japanese-anchangho-heungsadan", left: "안창호", right: "흥사단", era: "일제강점기", category: "인물-단체", priority: "A", explanation: "안창호는 샌프란시스코에서 흥사단을 창립하였다.", source: "한능검.md" },
  { id: "japanese-daehanin-national", left: "대한인 국민회", right: "미국 본토", era: "일제강점기", category: "단체-지역", priority: "B", explanation: "미국 본토에서는 대한인 국민회가 활동하였다.", source: "한능검.md" },
  { id: "japanese-daejoseon-gukmindan", left: "대조선 국민군단", right: "하와이", era: "일제강점기", category: "단체-지역", priority: "B", explanation: "하와이에는 대조선 국민군단이 조직되었다.", source: "한능검.md" },
  { id: "japanese-sungmu-mexico", left: "숭무학교", right: "멕시코", era: "일제강점기", category: "단체-지역", priority: "B", explanation: "멕시코에는 군사 교육 기관 숭무학교가 세워졌다.", source: "한능검.md" },
  { id: "japanese-gyeonghaksa-seogando", left: "경학사", right: "서간도", era: "일제강점기", category: "단체-지역", priority: "A", explanation: "서간도에는 한인 자치 기관 경학사가 조직되었다.", source: "한능검.md" },
  { id: "japanese-dokrip-uigunbu-imbyeongchan", left: "독립 의군부", right: "임병찬", era: "일제강점기", category: "단체-인물", priority: "S", explanation: "독립 의군부는 임병찬이 고종의 밀서를 받아 조직하였다.", source: "한능검.md" },
  { id: "japanese-sinhanchungnyeondang-gimgyusik", left: "신한청년당", right: "김규식", era: "일제강점기", category: "단체-활동", priority: "S", explanation: "신한청년당은 김규식을 파리 강화 회의에 보내 독립 청원서를 제출하게 하였다.", source: "한능검.md" },
  { id: "japanese-nobaekrin-flight-school", left: "노백린", right: "한인 비행 학교", era: "일제강점기", category: "인물-활동", priority: "A", explanation: "임시정부 군무총장 노백린은 김종림의 지원을 받아 캘리포니아 윌로우스에 한인 비행 학교를 세웠다.", source: "한능검.md" },
  { id: "japanese-daehangwangbok-park", left: "대한광복회", right: "박상진", era: "일제강점기", category: "단체-인물", priority: "S", explanation: "대한광복회는 박상진이 총사령으로 대구에서 조직을 주도하였다.", source: "한능검.md" },
  { id: "japanese-daehangwangbok-republic", left: "대한광복회", right: "공화 정체", era: "일제강점기", category: "단체-활동", priority: "A", explanation: "대한광복회는 공화 정체의 국민 국가 수립을 목표로 하였다.", source: "한능검.md" },
  { id: "japanese-naseokju-dongcheok", left: "나석주", right: "동양 척식 주식회사", era: "일제강점기", category: "인물-사건", priority: "S", explanation: "의열단원 나석주는 동양 척식 주식회사에 폭탄을 투척하였다.", source: "한능검.md" },
  { id: "japanese-gimwonbong-uireoldan", left: "김원봉", right: "의열단", era: "일제강점기", category: "인물-단체", priority: "S", explanation: "김원봉은 1919년 만주 길림에서 의열단 조직을 주도하고 단장으로 활동하였다.", source: "한능검.md" },
  { id: "japanese-gimwonbong-ganbu", left: "김원봉", right: "조선 혁명 간부 학교", era: "일제강점기", category: "인물-단체", priority: "A", explanation: "김원봉은 조선 혁명 간부 학교를 설립하였다.", source: "한능검.md" },
  { id: "japanese-daehan-dokripgun-hongbeomdo", left: "대한 독립군", right: "홍범도", era: "일제강점기", category: "단체-인물", priority: "S", explanation: "대한 독립군의 대표 지도자는 홍범도이다.", source: "한능검.md" },
  { id: "japanese-bongodong-hongbeomdo", left: "봉오동 전투", right: "홍범도", era: "일제강점기", category: "사건-인물", priority: "S", explanation: "홍범도가 이끄는 대한 독립군 등은 봉오동 전투에서 일본군을 격파하였다.", source: "한능검.md" },
  { id: "japanese-cheongsanri-gimjwajin", left: "청산리 대첩", right: "김좌진", era: "일제강점기", category: "사건-인물", priority: "S", explanation: "김좌진이 이끄는 북로 군정서군 등은 청산리 대첩에서 일본군을 격파하였다.", source: "한능검.md" },
  { id: "japanese-korean-dokripgun-jicheongcheon", left: "한국 독립군", right: "지청천", era: "일제강점기", category: "단체-인물", priority: "S", explanation: "한국 독립군은 지청천이 총사령관을 맡았다.", source: "한능검.md" },
  { id: "japanese-korean-dokripgun-ssangseongbo", left: "한국 독립군", right: "쌍성보 전투", era: "일제강점기", category: "단체-활동", priority: "S", explanation: "한국 독립군은 중국군과 연합하여 쌍성보 전투에서 일본군을 격퇴하였다.", source: "한능검.md" },
  { id: "japanese-korean-dokripgun-daejeonryeong", left: "한국 독립군", right: "대전자령 전투", era: "일제강점기", category: "단체-활동", priority: "S", explanation: "한국 독립군은 중국군과 연합하여 대전자령 전투에서 일본군을 격퇴하였다.", source: "한능검.md" },
  { id: "japanese-korean-gwangbokgun-jicheongcheon", left: "한국 광복군", right: "지청천", era: "일제강점기", category: "단체-인물", priority: "A", explanation: "1940년 충칭에서 창설된 한국 광복군의 총사령은 지청천이었다.", source: "한능검.md" },
  { id: "japanese-joseon-hyeokmyeonggun-yeongneungga", left: "조선 혁명군", right: "영릉가 전투", era: "일제강점기", category: "단체-활동", priority: "S", explanation: "조선 혁명군은 중국 의용군과 연합하여 영릉가 전투에서 승리하였다.", source: "한능검.md" },
  { id: "japanese-joseon-hyeokmyeonggun-heunggyeong", left: "조선 혁명군", right: "흥경성 전투", era: "일제강점기", category: "단체-활동", priority: "S", explanation: "조선 혁명군은 중국 의용군과 연합하여 흥경성 전투에서 승리하였다.", source: "한능검.md" },
  { id: "japanese-joseon-uiyongdae-gimwonbong", left: "조선 의용대", right: "김원봉", era: "일제강점기", category: "단체-인물", priority: "S", explanation: "김원봉을 중심으로 1938년 우한에서 조선 의용대가 창설되었다.", source: "한능검.md" },
  { id: "japanese-joseon-uiyongdae-wuhan", left: "조선 의용대", right: "우한", era: "일제강점기", category: "단체-활동", priority: "S", explanation: "조선 의용대는 1938년 우한에서 창설되었다.", source: "한능검.md" },
  { id: "japanese-joseon-uiyongdae-hogajang", left: "조선 의용대", right: "호가장 전투", era: "일제강점기", category: "단체-활동", priority: "A", explanation: "조선 의용대는 호가장 전투에서 활약하였다.", source: "한능검.md" },
  { id: "japanese-joseoneo-hangeul", left: "조선어 학회", right: "한글 맞춤법 통일안", era: "일제강점기", category: "단체-활동", priority: "A", explanation: "조선어 학회는 한글 맞춤법 통일안을 제정하였다.", source: "한능검.md" },
  { id: "japanese-joseoneo-dictionary", left: "조선어 학회", right: "조선말 큰사전", era: "일제강점기", category: "단체-활동", priority: "A", explanation: "조선어 학회는 조선말 큰사전 편찬을 추진하였다.", source: "한능검.md" },
  { id: "japanese-park-eunsik-hyeolsa", left: "박은식", right: "한국독립운동지혈사", era: "일제강점기", category: "인물-저술", priority: "A", explanation: "박은식은 한국독립운동지혈사를 저술하였다.", source: "한능검.md" },
  { id: "japanese-anhuije-baeksan", left: "안희제", right: "백산 상회", era: "일제강점기", category: "인물-단체", priority: "A", explanation: "안희제는 백산 상회를 설립하여 독립운동 자금을 마련하였다.", source: "한능검.md" },
  { id: "japanese-jeonginbo-joseonhak", left: "정인보", right: "조선학 운동", era: "일제강점기", category: "인물-활동", priority: "B", explanation: "정인보는 조선학 운동을 주도하고 여유당전서 간행에 참여하였다.", source: "한능검.md" },
  { id: "japanese-mitsuya-1925", left: "미쓰야 협정", right: "1925", era: "일제강점기", category: "사건-시기", priority: "B", explanation: "1925년 만주 군벌과 일제 사이에 미쓰야 협정이 체결되었다.", source: "한능검.md" },
  { id: "modern-usamguk-sinhan-gongsa", left: "미군정", right: "신한 공사", era: "현대사", category: "정부-정책", priority: "A", explanation: "미군정은 귀속 재산을 관리·처리하기 위해 신한 공사를 설립하였다.", source: "한능검.md" },
  { id: "modern-rhee-balchwe", left: "이승만", right: "발췌 개헌", era: "현대사", category: "인물-사건", priority: "S", explanation: "이승만 정부 시기 6·25 전쟁 중 발췌 개헌안이 통과되었다.", source: "한능검.md" },
  { id: "modern-rhee-jobongam", left: "이승만", right: "조봉암 구속", era: "현대사", category: "인물-사건", priority: "B", explanation: "이승만 정부 때 평화 통일론을 주장한 진보당 조봉암과 간부들이 구속되었다.", source: "한능검.md" },
  { id: "modern-419-gimjuyeol", left: "4·19 혁명", right: "김주열", era: "현대사", category: "사건-인물", priority: "S", explanation: "김주열이 최루탄에 맞아 숨진 채 발견되면서 4·19 혁명 시위가 확산되었다.", source: "한능검.md" },
  { id: "modern-second-republic-bicameral", left: "제2공화국", right: "민의원·참의원 양원제", era: "현대사", category: "정부-제도", priority: "B", explanation: "4·19 혁명 뒤 제2공화국의 국회는 민의원·참의원 양원제로 운영되었다.", source: "한능검.md" },
  { id: "modern-park-junta", left: "박정희", right: "국가재건최고회의", era: "현대사", category: "인물-제도", priority: "S", explanation: "5·16 군사 정변 세력이 국가재건최고회의를 구성하였고, 박정희는 1961년 7월 의장이 되었다.", source: "한능검.md" },
  { id: "modern-park-mincheong", left: "박정희", right: "민청학련 사건", era: "현대사", category: "인물-사건", priority: "B", explanation: "박정희 정부는 민청학련 사건과 인혁당 재건위 사건으로 반정부 인사와 학생 운동을 탄압하였다.", source: "한능검.md" },
  { id: "modern-chun-gukbowi", left: "전두환", right: "국가보위비상대책위원회", era: "현대사", category: "인물-제도", priority: "S", explanation: "신군부가 1980년 5월 국가보위비상대책위원회를 설치하였고, 전두환이 상임위원장을 맡았다.", source: "한능검.md" },
  { id: "modern-518-citizen-army", left: "5·18 민주화 운동", right: "시민군", era: "현대사", category: "사건-특징", priority: "S", explanation: "5·18 민주화 운동 때 광주에서 시민군이 조직되어 계엄군에 저항하였다.", source: "한능검.md" },
  { id: "modern-june-democracy-629", left: "6월 민주 항쟁", right: "6·29 민주화 선언", era: "현대사", category: "사건-결과", priority: "S", explanation: "6월 민주 항쟁의 결과 대통령 직선제 개헌을 수용한 6·29 민주화 선언이 발표되었다.", source: "한능검.md" },
  { id: "modern-chun-minimum-wage", left: "전두환", right: "최저임금위원회", era: "현대사", category: "인물-제도", priority: "C", explanation: "전두환 정부는 최저임금법을 제정하고 최저임금위원회를 설치하였다.", source: "한능검.md" },
  { id: "modern-roh-77", left: "노태우", right: "7·7 선언", era: "현대사", category: "인물-정책", priority: "S", explanation: "노태우 정부는 7·7 선언을 발표해 사회주의 국가와의 관계 개선과 남북 교류 확대를 추진하였다.", source: "한능검.md" },
  { id: "modern-roh-basic-agreement", left: "노태우", right: "남북 기본 합의서", era: "현대사", category: "인물-정책", priority: "S", explanation: "노태우 정부 때 남북 사이의 화해와 불가침 및 교류·협력에 관한 합의서가 채택되었다.", source: "한능검.md" },
  { id: "modern-roh-ganggyungdae", left: "노태우", right: "강경대 희생", era: "현대사", category: "인물-사건", priority: "C", explanation: "노태우 정부 때 1991년 민주화 시위 도중 강경대가 경찰 폭행으로 희생되었다.", source: "한능검.md" },
  { id: "modern-kimyoungsam-minjunochong", left: "김영삼 정부", right: "민주노총 창립", era: "현대사", category: "정부-사건", priority: "B", explanation: "김영삼 정부 때 1995년 민주노총 창립 대회가 열렸다.", source: "한능검.md" },
  { id: "modern-kimdaejoong-basic-life", left: "김대중 정부", right: "국민기초생활보장법", era: "현대사", category: "정부-정책", priority: "B", explanation: "김대중 정부 때 국민기초생활보장법이 제정되어 2000년 시행되었다.", source: "한능검.md" },
  { id: "modern-kimdaejoong-nosajeong", left: "김대중 정부", right: "노사정위원회", era: "현대사", category: "정부-제도", priority: "B", explanation: "김대중 정부는 외환 위기 극복과 사회적 합의를 위해 노사정위원회를 구성하였다.", source: "한능검.md" },
  { id: "modern-kimdaejoong-chile-sign", left: "김대중 정부", right: "한·칠레 FTA 서명", era: "현대사", category: "정부-정책", priority: "B", explanation: "한·칠레 자유 무역 협정은 김대중 정부 때인 2003년 2월 서명되었다.", source: "한능검.md" },
  { id: "modern-rohmoohyun-hojuje", left: "노무현 정부", right: "호주제 폐지", era: "현대사", category: "정부-정책", priority: "B", explanation: "노무현 정부 때 양성평등 실현을 위해 호주제가 폐지되었다.", source: "한능검.md" },
  { id: "modern-rohmoohyun-chile-ratify", left: "노무현 정부", right: "한·칠레 FTA 비준", era: "현대사", category: "정부-정책", priority: "B", explanation: "한·칠레 FTA는 노무현 정부 때 국회에서 비준되어 2004년 발효되었다.", source: "한능검.md" },
  { id: "modern-rohmoohyun-gaeseong", left: "노무현 정부", right: "개성 공업 지구 가동", era: "현대사", category: "정부-정책", priority: "B", explanation: "노무현 정부 때 개성 공업 지구가 조성되어 시범 가동과 본격 생산이 이루어졌다.", source: "한능검.md" },
  { id: "heritage-mireuksaji-baekje", left: "미륵사지 석탑", right: "백제", era: "문화재", category: "문화재-시대", priority: "S", explanation: "익산 미륵사지 석탑은 백제 무왕 때 건립된 것으로 보는 석탑이다.", source: "한능검.md" },
  { id: "heritage-mireuksaji-oldest", left: "미륵사지 석탑", right: "가장 오래된 석탑", era: "문화재", category: "문화재-특징", priority: "A", explanation: "미륵사지 석탑은 현존하는 우리나라 석탑 가운데 가장 오래된 석탑으로 평가된다.", source: "한능검.md" },
  { id: "heritage-gyeongcheonsa-goryeo", left: "경천사지 10층 석탑", right: "고려", era: "문화재", category: "문화재-시대", priority: "S", explanation: "개성 경천사지 10층 석탑은 고려 충목왕 때인 1348년에 세워졌다.", source: "한능검.md" },
  { id: "heritage-wongaksaji-joseon", left: "원각사지 10층 석탑", right: "조선", era: "문화재", category: "문화재-시대", priority: "S", explanation: "서울 원각사지 10층 석탑은 세조 때인 1467년에 조성되었다.", source: "한능검.md" },
  { id: "heritage-gyeongcheon-wongak-influence", left: "경천사지 10층 석탑", right: "원각사지 10층 석탑에 영향", era: "문화재", category: "문화재-영향", priority: "S", explanation: "원각사지 10층 석탑은 고려 경천사지 10층 석탑의 영향을 받았다.", source: "한능검.md" },
  { id: "heritage-wongaksaji-marble", left: "원각사지 10층 석탑", right: "대리석", era: "문화재", category: "문화재-특징", priority: "B", explanation: "원각사지 10층 석탑은 전체를 대리석으로 만든 10층 석탑이다.", source: "한능검.md" }
];
